main:
    host: 'localhost'
    user: 'administrator@vsphere.local'
    password: 'password'
    port: 443
    ignore_ssl: True
    vm_metrics:
    - 'cpu.usage.average'
    - 'cpu.usagemhz.average'
    - 'cpu.ready.summation'
    - 'mem.usage.average'
    - 'mem.swapinRate.average'
    - 'mem.swapoutRate.average'
    - 'mem.vmmemctl.average'
    - 'mem.consumed.average'
    - 'mem.overhead.average'
    - 'disk.usage.average'
